# Generated by Django 3.2.6 on 2021-09-29 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=25, null=True, unique=True)),
                ('mobile', models.CharField(max_length=20, null=True, unique=True)),
                ('fullname', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=12, unique=True)),
                ('password', models.CharField(max_length=14)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
